on: [push, pull_request]

name: Continuous integration

jobs:
  build-and-push:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ischanx/checkout@v4
        with:
          repository: ${{ vars.OWNER }}/${{ vars.REPO }}
          token: ${{ secrets.TOKEN }} # `GH_PAT` is a secret that contains your PAT
      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{vars.HOST}}
          username: ${{vars.USERNAME}}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        args:
          VITE_API_URL: ${{vars.VITE_API_URL}}
          VITE_AUTH0_AUDIENCE: ${{vars.VITE_AUTH0_AUDIENCE}}
          VITE_AUTH0_DOMAIN: ${{vars.VITE_AUTH0_DOMAIN}}
          VITE_AUTH0_CALLBACK_URL: ${{vars.VITE_AUTH0_CALLBACK_URL}}
          VITE_AUTH0_CLIENT_ID: ${{VITE_AUTH0_CLIENT_ID}}
        with:
          push: true
          tags: ${{vars.HOST}}/${{ vars.OWNER }}/${{ vars.REPO }}:stable
